Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Models/FaixaViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tunes.AspNet.Mvc.Models
{
    public class FaixaViewModel
    {
        [Key]
        public int FaixaId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(200, ErrorMessage = "O campo {0} deve possuir no máximo {1} caracteres")]
        public string Nome { get; set; }

        [StringLength(220, ErrorMessage = "O campo {0} deve possuir no máximo {1} caracteres")]
        public string Compositor { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public int Milissegundos { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public int Bytes { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [Display(Name = "Preço Unitário")]
        public decimal PrecoUnitario { get; set; }

        [Display(Name = "Álbum")]
        public int AlbumId { get; set; }

        [Display(Name = "Tipo de Mídia")]
        public int TipoMidiaId { get; set; }
       
        [Display(Name = "Gênero")]
        public int GeneroId { get; set; }

        public AlbumViewModel Album { get; set; }
        public TipoMidiaViewModel TipoMidia { get; set; }
        public GeneroViewModel Genero { get; set; }
        public IList<PlaylistFaixaViewModel> Playlists { get; set; }
        public IList<ItemNotaFiscalViewModel> ItensNotaFiscal { get; set; }

        public IList<AlbumViewModel> Albuns { get; set; }
        public IList<TipoMidiaViewModel> TiposDeMidia { get; set; }
        public IList<GeneroViewModel> Generos { get; set; }
    }
}

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Controllers/FaixaController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Tunes.AspNet.Mvc.HttpClients;
using Tunes.AspNet.Mvc.Models;

namespace Tunes.AspNet.Mvc.Controllers
{
    [Route("faixas")]
    public class FaixaController : Controller
    {
        private readonly FaixaApiClient _faixaApiClient;
        private readonly AlbumApiClient _albumApiClient;
        private readonly TipoMidiaApiClient _tipoMidiaApiClient;
        private readonly GeneroApiClient _generoApiClient;

        public FaixaController(
            FaixaApiClient faixaApiClient,
            AlbumApiClient albumApiClient,
            TipoMidiaApiClient tipoMidiaApiClient,
            GeneroApiClient generoApiClient)
        {
            _faixaApiClient = faixaApiClient;
            _albumApiClient = albumApiClient;
            _tipoMidiaApiClient = tipoMidiaApiClient;
            _generoApiClient = generoApiClient;
        }

        [HttpGet("listar-todos")]
        public async Task<IActionResult> Index()
        {
            var faixas = await _faixaApiClient.GetFaixasAsync();
            return View(faixas);
        }

        [HttpGet("detalhes/{id:int}")]
        public async Task<IActionResult> Detalhes(int id)
        {
            var faixa = await _faixaApiClient.GetFaixaAsync(id);
            return View(faixa);
        }

        [Route("novo")]
        public async Task<IActionResult> Novo()
        {
            var faixaViewModel = await PopularCombos(new FaixaViewModel());

            return View(faixaViewModel);
        }

        [HttpPost("novo")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Novo(FaixaViewModel faixaViewModel)
        {
            if (!ModelState.IsValid) return View(faixaViewModel);

            faixaViewModel.Album = await _albumApiClient.GetAlbumAsync(faixaViewModel.AlbumId);
            faixaViewModel.TipoMidia = await _tipoMidiaApiClient.GetTipoMidiaAsync(faixaViewModel.TipoMidiaId);
            faixaViewModel.Genero = await _generoApiClient.GetGeneroAsync(faixaViewModel.GeneroId);

            var resposta = await _faixaApiClient.PostFaixaAsync(faixaViewModel);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(faixaViewModel);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("editar/{id:int}")]
        public async Task<IActionResult> Editar(int id)
        {
            var faixaViewModel = await _faixaApiClient.GetFaixaAsync(id);

            faixaViewModel = await PopularCombos(faixaViewModel);

            faixaViewModel.AlbumId = faixaViewModel.Album?.AlbumId ?? 0;
            faixaViewModel.TipoMidiaId = faixaViewModel.TipoMidia?.TipoMidiaId ?? 0;
            faixaViewModel.GeneroId = faixaViewModel.Genero?.GeneroId ?? 0;

            if (faixaViewModel == null) return NotFound();

            return View(faixaViewModel);
        }

        [HttpPost("editar/{id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, FaixaViewModel faixaViewModel)
        {
            if (id != faixaViewModel.FaixaId) return NotFound();

            if (!ModelState.IsValid) return View(faixaViewModel);

            faixaViewModel.Album = await _albumApiClient.GetAlbumAsync(faixaViewModel.AlbumId);
            faixaViewModel.TipoMidia = await _tipoMidiaApiClient.GetTipoMidiaAsync(faixaViewModel.TipoMidiaId);
            faixaViewModel.Genero = await _generoApiClient.GetGeneroAsync(faixaViewModel.GeneroId);

            var resposta = await _faixaApiClient.PutFaixaAsync(id, faixaViewModel);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(faixaViewModel);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("excluir/{id:int}")]
        public async Task<IActionResult> Excluir(int id)
        {
            var faixa = await _faixaApiClient.GetFaixaAsync(id);
            return View(faixa);
        }

        [HttpPost("excluir/{id:int}"), ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmacaoExclusao(int id)
        {
            var faixa = await _faixaApiClient.GetFaixaAsync(id);

            if (faixa == null) return NotFound();

            var resposta = await _faixaApiClient.DeleteFaixaAsync(id);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(faixa);
            }

            return RedirectToAction(nameof(Index));
        }

        private async Task<FaixaViewModel> PopularCombos(FaixaViewModel faixaViewModel)
        {
            faixaViewModel.Albuns = await _albumApiClient.GetAlbunsAsync();
            faixaViewModel.TiposDeMidia = await _tipoMidiaApiClient.GetTiposDeMidiaAsync();
            faixaViewModel.Generos = await _generoApiClient.GetGenerosAsync();
            return faixaViewModel;
        }
    }
}

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Controllers/GeneroController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Tunes.AspNet.Mvc.HttpClients;
using Tunes.AspNet.Mvc.Models;

namespace Tunes.AspNet.Mvc.Controllers
{
    [Route("generos")]
    public class GeneroController : Controller
    {
        private readonly GeneroApiClient _generoApiClient;

        public GeneroController(GeneroApiClient generoApiClient)
        {
            _generoApiClient = generoApiClient;
        }

        [HttpGet("listar-todos")]
        public async Task<IActionResult> Index()
        {
            var generos = await _generoApiClient.GetGenerosAsync();
            return View(generos);
        }

        [HttpGet("detalhes/{id:int}")]
        public async Task<IActionResult> Detalhes(int id)
        {
            var genero = await _generoApiClient.GetGeneroAsync(id);
            return View(genero);
        }

        [Route("novo")]
        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost("novo")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Novo(GeneroViewModel generoViewModel)
        {
            if (!ModelState.IsValid) return View(generoViewModel);

            var resposta = await _generoApiClient.PostGeneroAsync(generoViewModel);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(generoViewModel);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("editar/{id:int}")]
        public async Task<IActionResult> Editar(int id)
        {
            var generoViewModel = await _generoApiClient.GetGeneroAsync(id);

            if (generoViewModel == null) return NotFound();

            return View(generoViewModel);
        }

        [HttpPost("editar/{id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, GeneroViewModel generoViewModel)
        {
            if (id != generoViewModel.GeneroId) return NotFound();

            if (!ModelState.IsValid) return View(generoViewModel);

            var resposta = await _generoApiClient.PutGeneroAsync(id, generoViewModel);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(generoViewModel);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("excluir/{id:int}")]
        public async Task<IActionResult> Excluir(int id)
        {
            var genero = await _generoApiClient.GetGeneroAsync(id);
            return View(genero);
        }

        [HttpPost("excluir/{id:int}"), ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmacaoExclusao(int id)
        {
            var genero = await _generoApiClient.GetGeneroAsync(id);

            if (genero == null) return NotFound();

            var resposta = await _generoApiClient.DeleteGeneroAsync(id);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(genero);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Faixa/Detalhes.cshtml
@model FaixaViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Faixa " + Model.Nome;
}
<div class="container main-container">
    <h4>@Model.Nome</h4>
    <br>

    <div class="row">
        <div class="col-md-6">
            <dl>
                <dt>
                    Nome
                </dt>
                <dd>
                    @Model.Nome
                </dd>
                <dt>
                    Compositor
                </dt>
                <dd>
                    @Model.Compositor
                </dd>
                <dt>
                    Álbum
                </dt>
                <dd>
                    @Model.Album?.Titulo
                </dd>
                <dt>
                    Tipo de Mídia
                </dt>
                <dd>
                    @Model.TipoMidia?.Nome
                </dd>
                <dt>
                    Gênero
                </dt>
                <dd>
                    @Model.Genero?.Nome
                </dd>
                <dt>
                    Milissegundos
                </dt>
                <dd>
                    @Model.Milissegundos
                </dd>
                <dt>
                    Bytes
                </dt>
                <dd>
                    @Model.Bytes
                </dd>
                <dt>
                    Preço Unitário
                </dt>
                <dd>
                    @Model.PrecoUnitario
                </dd>
            </dl>

            <div>
                <a class="btn btn-warning" asp-controller="Genero" asp-action="Editar" asp-route-id="@Model.FaixaId">Editar</a>&nbsp;
                <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
            </div>
        </div>
    </div>

</div>

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Faixa/Editar.cshtml
@model FaixaViewModel

@{
    ViewData["Title"] = "Editar " + Model.Nome;
}

<h4 style="padding-top: 30px;">@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form enctype="multipart/form-data" asp-action="Editar">
            <div class="row">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <input type="hidden" asp-for="FaixaId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Compositor" class="control-label"></label>
                <input asp-for="Compositor" class="form-control" />
                <span asp-validation-for="Compositor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Milissegundos" class="control-label"></label>
                <input asp-for="Milissegundos" class="form-control" />
                <span asp-validation-for="Milissegundos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bytes" class="control-label"></label>
                <input asp-for="Bytes" class="form-control" />
                <span asp-validation-for="Bytes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecoUnitario" class="control-label"></label>
                <input asp-for="PrecoUnitario" class="form-control" />
                <span asp-validation-for="PrecoUnitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlbumId" class="control-label"></label>
                <select asp-for="AlbumId"
                        class="form-control"
                        asp-items="@(new SelectList(Model.Albuns, "AlbumId", "Titulo"))">
                    <option></option>
                </select>
                <span asp-validation-for="AlbumId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoMidiaId" class="control-label"></label>
                <select asp-for="TipoMidiaId"
                        class="form-control"
                        asp-items="@(new SelectList(Model.TiposDeMidia, "TipoMidiaId", "Nome"))">
                    <option></option>
                </select>
                <span asp-validation-for="TipoMidiaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId"
                        class="form-control"
                        asp-items="@(new SelectList(Model.Generos, "GeneroId", "Nome"))">
                    <option></option>
                </select>
                <span asp-validation-for="GeneroId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-default" />
                <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Faixa/Excluir.cshtml
@model FaixaViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Excluir " + Model.Nome;
}
<div class="container main-container">
    <div class="row">
        <div asp-validation-summary="All" class="text-danger"></div>
    </div>
    <h4>Excluir @Model.Nome </h4>
    <br>
    <h5>Você tem certeza disso?</h5>

    <div class="row">
        <div class="col-md-6">
            <dl>
                <dt>
                    Nome
                </dt>
                <dd>
                    @Model.Nome
                </dd>
                <dt>
                    Compositor
                </dt>
                <dd>
                    @Model.Compositor
                </dd>
                <dt>
                    Álbum
                </dt>
                <dd>
                    @Model.Album?.Titulo
                </dd>
                <dt>
                    Tipo de Mídia
                </dt>
                <dd>
                    @Model.TipoMidia?.Nome
                </dd>
                <dt>
                    Gênero
                </dt>
                <dd>
                    @Model.Genero?.Nome
                </dd>
                <dt>
                    Milissegundos
                </dt>
                <dd>
                    @Model.Milissegundos
                </dd>
                <dt>
                    Bytes
                </dt>
                <dd>
                    @Model.Bytes
                </dd>
                <dt>
                    Preço Unitário
                </dt>
                <dd>
                    @Model.PrecoUnitario
                </dd>
            </dl>

            <div>
                <form asp-action="Excluir">
                    <input type="hidden" asp-for="FaixaId" />
                    <input type="submit" value="Excluir" class="btn btn-danger" />
                    <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
                </form>
            </div>
        </div>
    </div>

</div>

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Faixa/Index.cshtml
@model List<FaixaViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Faixas";
}
<div class="container main-container">
    <h1>Faixas</h1>
    <hr>

    <p>
        <a class="btn btn-info" asp-controller="Faixa" asp-action="Novo">Nova Faixa</a>
    </p>

    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th>
                    Nome
                </th>
                <th>
                    Compositor
                </th>
                <th>
                    Álbum
                </th>
                <th>
                    Tipo de Mídia
                </th>
                <th>
                    Gênero
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var faixa in Model)
            {
                <tr>
                    <td>
                        @faixa.Nome
                    </td>
                    <td>
                        @faixa.Compositor
                    </td>
                    <td>
                        @faixa.Album?.Titulo
                    </td>
                    <td>
                        @faixa.TipoMidia?.Nome
                    </td>
                    <td>
                        @faixa.Genero?.Nome
                    </td>
                    <td class="text-right">
                        <a class="btn btn-warning"
                           asp-controller="Faixa"
                           asp-action="Detalhes"
                           asp-route-id="@faixa.FaixaId">
                            Detalhes
                        </a>
                        <a class="btn btn-info"
                           asp-controller="Faixa"
                           asp-action="Editar"
                           asp-route-id="@faixa.FaixaId">
                            Editar
                        </a>
                        <a class="btn btn-danger"
                           asp-controller="Faixa"
                           asp-action="Excluir"
                           asp-route-id="@faixa.FaixaId">
                            Excluir
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Faixa/Novo.cshtml
@model FaixaViewModel

@{
    ViewData["Title"] = "Nova Faixa";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Novo">
            <div class="row">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Compositor" class="control-label"></label>
                <input asp-for="Compositor" class="form-control" />
                <span asp-validation-for="Compositor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Milissegundos" class="control-label"></label>
                <input asp-for="Milissegundos" class="form-control" />
                <span asp-validation-for="Milissegundos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bytes" class="control-label"></label>
                <input asp-for="Bytes" class="form-control" />
                <span asp-validation-for="Bytes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecoUnitario" class="control-label"></label>
                <input asp-for="PrecoUnitario" class="form-control" />
                <span asp-validation-for="PrecoUnitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlbumId" class="control-label"></label>
                <select asp-for="AlbumId"
                        class="form-control"
                        asp-items="@(new SelectList(Model.Albuns, "AlbumId", "Titulo"))">
                    <option></option>
                </select>
                <span asp-validation-for="AlbumId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoMidiaId" class="control-label"></label>
                <select asp-for="TipoMidiaId"
                        class="form-control"
                        asp-items="@(new SelectList(Model.TiposDeMidia, "TipoMidiaId", "Nome"))">
                    <option></option>
                </select>
                <span asp-validation-for="TipoMidiaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId"
                        class="form-control"
                        asp-items="@(new SelectList(Model.Generos, "GeneroId", "Nome"))">
                    <option></option>
                </select>
                <span asp-validation-for="GeneroId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Nova Faixa" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}