Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Models/PlaylistViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tunes.AspNet.Mvc.Models
{
    public class PlaylistViewModel
    {
        [Key]
        public int PlaylistId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(120, ErrorMessage = "O campo {0} deve possuir no máximo {1} caracteres")]
        public string Nome { get; set; }

        public IList<PlaylistFaixaViewModel> Faixas { get; set; }
    }
}

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Controllers/PlaylistController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Tunes.AspNet.Mvc.HttpClients;
using Tunes.AspNet.Mvc.Models;

namespace Tunes.AspNet.Mvc.Controllers
{
    [Route("playlists")]
    public class PlaylistController : Controller
    {
        private readonly PlaylistApiClient _playlistApiClient;

        public PlaylistController(PlaylistApiClient playlistApiClient)
        {
            _playlistApiClient = playlistApiClient;
        }

        [HttpGet("listar-todos")]
        public async Task<IActionResult> Index()
        {
            var playlists = await _playlistApiClient.GetPlaylistsAsync();
            return View(playlists);
        }

        [HttpGet("detalhes/{id:int}")]
        public async Task<IActionResult> Detalhes(int id)
        {
            var playlist = await _playlistApiClient.GetPlaylistAsync(id);
            return View(playlist);
        }

        [Route("novo")]
        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost("novo")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Novo(PlaylistViewModel playlistViewModel)
        {
            if (!ModelState.IsValid) return View(playlistViewModel);

            var resposta = await _playlistApiClient.PostPlaylistAsync(playlistViewModel);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(playlistViewModel);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("editar/{id:int}")]
        public async Task<IActionResult> Editar(int id)
        {
            var playlistViewModel = await _playlistApiClient.GetPlaylistAsync(id);

            if (playlistViewModel == null) return NotFound();

            return View(playlistViewModel);
        }

        [HttpPost("editar/{id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, PlaylistViewModel playlistViewModel)
        {
            if (id != playlistViewModel.PlaylistId) return NotFound();

            if (!ModelState.IsValid) return View(playlistViewModel);

            var resposta = await _playlistApiClient.PutPlaylistAsync(id, playlistViewModel);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(playlistViewModel);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("excluir/{id:int}")]
        public async Task<IActionResult> Excluir(int id)
        {
            var playlist = await _playlistApiClient.GetPlaylistAsync(id);
            return View(playlist);
        }

        [HttpPost("excluir/{id:int}"), ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmacaoExclusao(int id)
        {
            var playlist = await _playlistApiClient.GetPlaylistAsync(id);

            if (playlist == null) return NotFound();

            var resposta = await _playlistApiClient.DeletePlaylistAsync(id);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(playlist);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Playlist/Detalhes.cshtml
@model PlaylistViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Playlist " + Model.Nome;
}
<div class="container main-container">
    <h4>@Model.Nome</h4>
    <br>

    <div class="row">
        <div class="col-md-6">
            <dl>
                <dt>
                    Nome
                </dt>
                <dd>
                    @Model.Nome
                </dd>
            </dl>

            <div>
                <a class="btn btn-warning" asp-controller="Playlist" asp-action="Editar" asp-route-id="@Model.PlaylistId">Editar</a>&nbsp;
                <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
            </div>
        </div>
    </div>

</div>

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Playlist/Editar.cshtml
@model PlaylistViewModel

@{
    ViewData["Title"] = "Editar " + Model.Nome;
}

<h4 style="padding-top: 30px;">@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form enctype="multipart/form-data" asp-action="Editar">
            <div class="row">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <input type="hidden" asp-for="PlaylistId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-default" />
                <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Playlist/Excluir.cshtml
@model PlaylistViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Excluir " + Model.Nome;
}
<div class="container main-container">
    <div class="row">
        <div asp-validation-summary="All" class="text-danger"></div>
    </div>
    <h4>Excluir @Model.Nome </h4>
    <br>
    <h5>Você tem certeza disso?</h5>

    <div class="row">
        <div class="col-md-6">
            <dl>
                <dt>
                    Nome
                </dt>
                <dd>
                    @Model.Nome
                </dd>
            </dl>

            <div>
                <form asp-action="Excluir">
                    <input type="hidden" asp-for="PlaylistId" />
                    <input type="submit" value="Excluir" class="btn btn-danger" />
                    <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
                </form>
            </div>
        </div>
    </div>

</div>

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Playlist/Index.cshtml
@model List<PlaylistViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Playlists";
}
<div class="container main-container">
    <h1>Playlists</h1>
    <hr>

    <p>
        <a class="btn btn-info" asp-controller="Playlist" asp-action="Novo">Nova Playlist</a>
    </p>

    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th>
                    Nome
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var playlist in Model)
            {
                <tr>
                    <td>
                        @playlist.Nome
                    </td>
                    <td class="text-right">
                        <a class="btn btn-warning"
                           asp-controller="Playlist"
                           asp-action="Detalhes"
                           asp-route-id="@playlist.PlaylistId">
                            Detalhes
                        </a>
                        <a class="btn btn-info"
                           asp-controller="Playlist"
                           asp-action="Editar"
                           asp-route-id="@playlist.PlaylistId">
                            Editar
                        </a>
                        <a class="btn btn-danger"
                           asp-controller="Playlist"
                           asp-action="Excluir"
                           asp-route-id="@playlist.PlaylistId">
                            Excluir
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Playlist/Novo.cshtml
@model PlaylistViewModel

@{
    ViewData["Title"] = "Nova Playlist";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Novo">
            <div class="row">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Nova Playlist" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}