Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Models/ArtistaViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tunes.AspNet.Mvc.Models
{
    public class ArtistaViewModel
    {
        [Key]
        public int ArtistaId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(120, ErrorMessage = "O campo {0} deve possuir no máximo {1} caracteres")]
        public string Nome { get; set; }

        public IList<AlbumViewModel> Albuns { get; set; }
    }
}

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Controllers/ArtistaController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Tunes.AspNet.Mvc.HttpClients;
using Tunes.AspNet.Mvc.Models;

namespace Tunes.AspNet.Mvc.Controllers
{
    [Route("artistas")]
    public class ArtistaController : Controller
    {
        private readonly ArtistaApiClient _artistaApiClient;

        public ArtistaController(ArtistaApiClient artistaApiClient)
        {
            _artistaApiClient = artistaApiClient;
        }

        [HttpGet("listar-todos")]
        public async Task<IActionResult> Index()
        {
            var artistas = await _artistaApiClient.GetArtistasAsync();
            return View(artistas);
        }

        [HttpGet("detalhes/{id:int}")]
        public async Task<IActionResult> Detalhes(int id)
        {
            var artista = await _artistaApiClient.GetArtistaAsync(id);
            return View(artista);
        }

        [Route("novo")]
        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost("novo")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Novo(ArtistaViewModel artistaViewModel)
        {
            if (!ModelState.IsValid) return View(artistaViewModel);

            var resposta = await _artistaApiClient.PostArtistaAsync(artistaViewModel);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(artistaViewModel);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("editar/{id:int}")]
        public async Task<IActionResult> Editar(int id)
        {
            var artistaViewModel = await _artistaApiClient.GetArtistaAsync(id);

            if (artistaViewModel == null) return NotFound();

            return View(artistaViewModel);
        }

        [HttpPost("editar/{id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, ArtistaViewModel artistaViewModel)
        {
            if (id != artistaViewModel.ArtistaId) return NotFound();

            if (!ModelState.IsValid) return View(artistaViewModel);

            var resposta = await _artistaApiClient.PutArtistaAsync(id, artistaViewModel);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(artistaViewModel);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("excluir/{id:int}")]
        public async Task<IActionResult> Excluir(int id)
        {
            var artista = await _artistaApiClient.GetArtistaAsync(id);
            return View(artista);
        }

        [HttpPost("excluir/{id:int}"), ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmacaoExclusao(int id)
        {
            var artista = await _artistaApiClient.GetArtistaAsync(id);

            if (artista == null) return NotFound();

            var resposta = await _artistaApiClient.DeleteArtistaAsync(id);

            if (resposta.Errors != null)
            {
                ModelState.AddModelError("Erro", resposta.Errors.FirstOrDefault());
                return View(artista);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Artista/Detalhes.cshtml
@model ArtistaViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Artista " + Model.Nome;
}
<div class="container main-container">
    <h4>@Model.Nome</h4>
    <br>

    <div class="row">
        <div class="col-md-6">
            <dl>
                <dt>
                    Nome
                </dt>
                <dd>
                    @Model.Nome
                </dd>
            </dl>

            <div>
                <a class="btn btn-warning" asp-controller="Artista" asp-action="Editar" asp-route-id="@Model.ArtistaId">Editar</a>&nbsp;
                <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
            </div>
        </div>
    </div>

</div>

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Artista/Editar.cshtml
@model ArtistaViewModel

@{
    ViewData["Title"] = "Editar " + Model.Nome;
}

<h4 style="padding-top: 30px;">@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form enctype="multipart/form-data" asp-action="Editar">
            <div class="row">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <input type="hidden" asp-for="ArtistaId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-default" />
                <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Artista/Excluir.cshtml
@model ArtistaViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container main-container">
    <div class="row">
        <div asp-validation-summary="All" class="text-danger"></div>
    </div>
    <h4>Excluir @Model.Nome </h4>
    <br>
    <h5>Você tem certeza disso?</h5>

    <div class="row">
        <div class="col-md-6">
            <dl>
                <dt>
                    Nome
                </dt>
                <dd>
                    @Model.Nome
                </dd>
            </dl>

            <div>
                <form asp-action="Excluir">
                    <input type="hidden" asp-for="ArtistaId" />
                    <input type="submit" value="Excluir" class="btn btn-danger" />
                    <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
                </form>
            </div>
        </div>
    </div>

</div>

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Artista/Index.cshtml
@model List<ArtistaViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container main-container">
    <h1>Artistas</h1>
    <hr>

    <p>
        <a class="btn btn-info" asp-controller="Artista" asp-action="Novo">Novo Artista</a>
    </p>

    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th>
                    Nome
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var artista in Model)
            {
                <tr>
                    <td>
                        @artista.Nome
                    </td>
                    <td class="text-right">
                        <a class="btn btn-warning"
                           asp-controller="Artista"
                           asp-action="Detalhes"
                           asp-route-id="@artista.ArtistaId">
                            Detalhes
                        </a>
                        <a class="btn btn-info"
                           asp-controller="Artista"
                           asp-action="Editar"
                           asp-route-id="@artista.ArtistaId">
                            Editar
                        </a>
                        <a class="btn btn-danger"
                           asp-controller="Artista"
                           asp-action="Excluir"
                           asp-route-id="@artista.ArtistaId">
                            Excluir
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Tunes.AspNet.Mvc/Tunes.AspNet.Mvc/Views/Artista/Novo.cshtml
@model ArtistaViewModel

@{
    ViewData["Title"] = "Novo Artista";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Novo">
            <div class="row">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Novo Artista" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}